name: Release Action
on:
  release:
    types: [created]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Display Message on Release
        run: echo "Hello when a new release is created"